package configcat

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/config"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccSettingValueV2StringResource(t *testing.T) {
	const configId = "08dc1bfa-b8b0-45f0-8127-fac0de7a37ac"
	const environmentId = "08d86d63-2726-47cd-8bfc-59608ecb91e2"
	const testResourceName = "configcat_setting_value_v2.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigFile: config.TestNameFile("value_only.tf"),
				ConfigVariables: config.Variables{
					"config_id":      config.StringVariable(configId),
					"environment_id": config.StringVariable(environmentId),
					"value":          config.StringVariable("a"),
				},
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet(testResourceName, ID),
					resource.TestCheckResourceAttr(testResourceName, DefaultValue+"."+StringValue, "a"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".#", "0"),
				),
			},
			{
				ConfigFile: config.TestNameFile("value_only.tf"),
				ConfigVariables: config.Variables{
					"config_id":      config.StringVariable(configId),
					"environment_id": config.StringVariable(environmentId),
					"value":          config.StringVariable("a"),
				},
				ResourceName:            testResourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{InitOnly},
			},
			{
				ConfigFile: config.TestNameFile("value_only.tf"),
				ConfigVariables: config.Variables{
					"config_id":      config.StringVariable(configId),
					"environment_id": config.StringVariable(environmentId),
					"value":          config.StringVariable("b"),
				},
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet(testResourceName, ID),
					resource.TestCheckResourceAttr(testResourceName, DefaultValue+"."+StringValue, "b"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".#", "0"),
				),
			},
			{
				ConfigFile: config.TestNameFile("value_only.tf"),
				ConfigVariables: config.Variables{
					"config_id":      config.StringVariable(configId),
					"environment_id": config.StringVariable(environmentId),
					"value":          config.StringVariable("b"),
				},
				ResourceName:            testResourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{InitOnly},
			},
			{
				ConfigFile: config.TestNameFile("with_percentage.tf"),
				ConfigVariables: config.Variables{
					"config_id":      config.StringVariable(configId),
					"environment_id": config.StringVariable(environmentId),
					"value":          config.StringVariable("c"),
					"percentage":     config.IntegerVariable(10),
				},
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet(testResourceName, ID),
					resource.TestCheckResourceAttr(testResourceName, DefaultValue+"."+StringValue, "c"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".#", "1"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRulePercentageOptions+".#", "2"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRulePercentageOptions+".0."+TargetingRulePercentageOptionPercentage, "10"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRulePercentageOptions+".0."+TargetingRulePercentageOptionValue+"."+StringValue, "tpa"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRulePercentageOptions+".1."+TargetingRulePercentageOptionPercentage, "90"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRulePercentageOptions+".1."+TargetingRulePercentageOptionValue+"."+StringValue, "tpb"),
				),
			},
			{
				ConfigFile: config.TestNameFile("with_percentage.tf"),
				ConfigVariables: config.Variables{
					"config_id":      config.StringVariable(configId),
					"environment_id": config.StringVariable(environmentId),
					"value":          config.StringVariable("c"),
					"percentage":     config.IntegerVariable(10),
				},
				ResourceName:            testResourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{InitOnly},
			},
			{
				ConfigFile: config.TestNameFile("with_percentage.tf"),
				ConfigVariables: config.Variables{
					"config_id":      config.StringVariable(configId),
					"environment_id": config.StringVariable(environmentId),
					"value":          config.StringVariable("d"),
					"percentage":     config.IntegerVariable(20),
				},
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet(testResourceName, ID),
					resource.TestCheckResourceAttr(testResourceName, DefaultValue+"."+StringValue, "d"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".#", "1"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRulePercentageOptions+".#", "2"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRulePercentageOptions+".0."+TargetingRulePercentageOptionPercentage, "20"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRulePercentageOptions+".0."+TargetingRulePercentageOptionValue+"."+StringValue, "tpa"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRulePercentageOptions+".1."+TargetingRulePercentageOptionPercentage, "80"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRulePercentageOptions+".1."+TargetingRulePercentageOptionValue+"."+StringValue, "tpb"),
				),
			},
			{
				ConfigFile: config.TestNameFile("with_percentage.tf"),
				ConfigVariables: config.Variables{
					"config_id":      config.StringVariable(configId),
					"environment_id": config.StringVariable(environmentId),
					"value":          config.StringVariable("d"),
					"percentage":     config.IntegerVariable(20),
				},
				ResourceName:            testResourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{InitOnly},
			},
			{
				ConfigFile: config.TestNameFile("with_rule.tf"),
				ConfigVariables: config.Variables{
					"config_id":      config.StringVariable(configId),
					"environment_id": config.StringVariable(environmentId),
				},
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet(testResourceName, ID),
					resource.TestCheckResourceAttr(testResourceName, DefaultValue+"."+StringValue, "va"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".#", "1"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRulePercentageOptions+".#", "0"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".#", "1"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleValue+"."+StringValue, "tb"),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRuleSegmentCondition),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRulePrerequisiteFlagCondition),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonAttribute, "email"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparator, "sensitiveTextEquals"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+StringValue, "@configcat.com"),
				),
			},
			{
				ConfigFile: config.TestNameFile("with_rule.tf"),
				ConfigVariables: config.Variables{
					"config_id":      config.StringVariable(configId),
					"environment_id": config.StringVariable(environmentId),
				},
				ResourceName:            testResourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{InitOnly},
			},
			{
				ConfigFile: config.TestNameFile("with_rules.tf"),
				ConfigVariables: config.Variables{
					"config_id":      config.StringVariable(configId),
					"environment_id": config.StringVariable(environmentId),
				},
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet(testResourceName, ID),
					resource.TestCheckResourceAttr(testResourceName, DefaultValue+"."+StringValue, "va"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".#", "2"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRulePercentageOptions+".#", "0"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".#", "1"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleValue+"."+StringValue, "tc"),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRuleSegmentCondition),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRulePrerequisiteFlagCondition),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonAttribute, "email"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparator, "sensitiveTextEquals"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+StringValue, "jane@configcat.com"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRulePercentageOptions+".#", "0"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".#", "1"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleValue+"."+StringValue, "td"),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleSegmentCondition),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRulePrerequisiteFlagCondition),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonAttribute, "email"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparator, "containsAnyOf"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+ListValues+".#", "2"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+ListValues+".0."+ListValueValue, "@configcat.com"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+ListValues+".0."+ListValueHint, "the greatest company of the world"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+ListValues+".1."+ListValueValue, "@example.com"),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+ListValues+".1."+ListValueHint),
				),
			},
			{
				ConfigFile: config.TestNameFile("with_rules.tf"),
				ConfigVariables: config.Variables{
					"config_id":      config.StringVariable(configId),
					"environment_id": config.StringVariable(environmentId),
				},
				ResourceName:            testResourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{InitOnly},
			},
			{
				ConfigFile: config.TestNameFile("with_rules_and_percentage.tf"),
				ConfigVariables: config.Variables{
					"config_id":      config.StringVariable(configId),
					"environment_id": config.StringVariable(environmentId),
					"percentage":     config.IntegerVariable(27),
				},
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet(testResourceName, ID),
					resource.TestCheckResourceAttr(testResourceName, DefaultValue+"."+StringValue, "vc"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".#", "3"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRulePercentageOptions+".#", "0"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".#", "1"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleValue+"."+StringValue, "te"),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRuleSegmentCondition),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRulePrerequisiteFlagCondition),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonAttribute, "email"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparator, "sensitiveTextEquals"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+StringValue, "@configcat.com"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRulePercentageOptions+".#", "0"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".#", "1"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleValue+"."+StringValue, "tf"),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleSegmentCondition),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRulePrerequisiteFlagCondition),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonAttribute, "color"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparator, "isOneOf"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+ListValues+".#", "2"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+ListValues+".0."+ListValueValue, "#000000"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+ListValues+".0."+ListValueHint, "black"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+ListValues+".1."+ListValueValue, "red"),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+ListValues+".1."+ListValueHint),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".2."+TargetingRulePercentageOptions+".#", "2"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".2."+TargetingRulePercentageOptions+".0."+TargetingRulePercentageOptionPercentage, "27"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".2."+TargetingRulePercentageOptions+".0."+TargetingRulePercentageOptionValue+"."+StringValue, "tpa"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".2."+TargetingRulePercentageOptions+".1."+TargetingRulePercentageOptionPercentage, "73"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".2."+TargetingRulePercentageOptions+".1."+TargetingRulePercentageOptionValue+"."+StringValue, "tpb"),
				),
			},
			{
				ConfigFile: config.TestNameFile("with_rules_and_percentage.tf"),
				ConfigVariables: config.Variables{
					"config_id":      config.StringVariable(configId),
					"environment_id": config.StringVariable(environmentId),
					"percentage":     config.IntegerVariable(27),
				},
				ResourceName:            testResourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{InitOnly},
			},
			{
				ConfigFile: config.TestNameFile("with_rules_and_percentage.tf"),
				ConfigVariables: config.Variables{
					"config_id":      config.StringVariable(configId),
					"environment_id": config.StringVariable(environmentId),
					"percentage":     config.IntegerVariable(37),
				},
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet(testResourceName, ID),
					resource.TestCheckResourceAttr(testResourceName, DefaultValue+"."+StringValue, "vc"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".#", "3"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRulePercentageOptions+".#", "0"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".#", "1"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleValue+"."+StringValue, "te"),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRuleSegmentCondition),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRulePrerequisiteFlagCondition),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonAttribute, "email"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparator, "sensitiveTextEquals"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".0."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+StringValue, "@configcat.com"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRulePercentageOptions+".#", "0"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".#", "1"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleValue+"."+StringValue, "tf"),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleSegmentCondition),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRulePrerequisiteFlagCondition),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonAttribute, "color"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparator, "isOneOf"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+ListValues+".#", "2"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+ListValues+".0."+ListValueValue, "#000000"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+ListValues+".0."+ListValueHint, "black"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+ListValues+".1."+ListValueValue, "red"),
					resource.TestCheckNoResourceAttr(testResourceName, TargetingRules+".1."+TargetingRuleConditions+".0."+TargetingRuleUserCondition+"."+TargetingRuleUserConditionComparisonValue+"."+ListValues+".1."+ListValueHint),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".2."+TargetingRulePercentageOptions+".#", "2"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".2."+TargetingRulePercentageOptions+".0."+TargetingRulePercentageOptionPercentage, "37"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".2."+TargetingRulePercentageOptions+".0."+TargetingRulePercentageOptionValue+"."+StringValue, "tpa"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".2."+TargetingRulePercentageOptions+".1."+TargetingRulePercentageOptionPercentage, "63"),
					resource.TestCheckResourceAttr(testResourceName, TargetingRules+".2."+TargetingRulePercentageOptions+".1."+TargetingRulePercentageOptionValue+"."+StringValue, "tpb"),
				),
			},
			{
				ConfigFile: config.TestNameFile("with_rules_and_percentage.tf"),
				ConfigVariables: config.Variables{
					"config_id":      config.StringVariable(configId),
					"environment_id": config.StringVariable(environmentId),
					"value":          config.IntegerVariable(8),
					"percentage":     config.IntegerVariable(37),
				},
				ResourceName:            testResourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{InitOnly},
			},
		},
	})
}
